[package]
name = "advent-of-code"
version = "0.1.0"
authors = ["joemspalding"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"regex" = "1"
"string-builder" = "0.2.0"
"itertools" = "0.9.0"